fail-on-severity: 'high'

license-check: true
vulnerability-check: true

fail-on-scopes:
  - runtime
  - development
  - unknown

allow-licenses:
  - MIT
  - Apache-2.0
  - BSD-3-Clause
  - ISC

# deny-licenses:

# allow-ghsas:


allow-dependencies-licenses:
  - pkg:npm/@myorg/mypackage
  - pkg:npm/packagename
  - pkg:githubactions/owner/repo@2.0.0

comment-summary-in-pr: 'on-failure'

warn-only: false

show-openssf-scorecard: true

warn-on-openssf-scorecard-level: 3

show-patched-versions: true