name: SonarQube Scan

on:
    workflow_call:
        inputs:
            config-path:
                required: false
                type: string
            PROJECTID: 
                required: false
                type: string
            cache-folder:
                required: false
                type: string
            environment:
                required: false
                type: string

jobs:
    sonarqube:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Code
          uses: actions/checkout@v6
          with:
           fetch-depth: 0 # Essential for SonarQube to perform proper branch analysis

        - name: SonarQube Scan
          uses: SonarSource/sonarqube-scan-action@v7.1.0 # Latest
          env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
          with:
            projectBaseDir: ${{ inputs.config-path || './config-sonar/' }}
            args: >
                -Dsonar.terraform.provider.gcp.version=latest

        
        - name: SonarQube Quality Gate Check
          uses: SonarSource/sonarqube-quality-gate-action@v1.2.0 # Latest
          timeout-minutes: 5
          env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}